import {
  Organization,
  Region,
  PropertyArea,
  User,
  Project,
  ProjectTower,
  ProjectUnit,
  Person,
  ExternalOrganization,
  EntityRelationship,
  PropertyFact,
  UnitPriceHistory,
  Lead,
  Activity,
  Task,
  CRMDocument,
  SellerOpportunity,
  SiteVisitBriefing,
} from "../types/crm";

export const INITIAL_ORG: Organization = {
  id: "org-dlf-partners",
  name: "Apex Realty Advisors",
  slug: "apex-realty",
};

export const INITIAL_REGIONS: Region[] = [
  { id: "reg-gurgaon", orgId: "org-dlf-partners", name: "Gurgaon Hub", code: "GGN", activeLeadsCount: 142 },
  { id: "reg-noida", orgId: "org-dlf-partners", name: "Noida Hub", code: "NDA", activeLeadsCount: 86 },
  { id: "reg-delhi", orgId: "org-dlf-partners", name: "Delhi Luxury Hub", code: "DL", activeLeadsCount: 48 },
];

export const INITIAL_AREAS: PropertyArea[] = [
  {
    id: "area-gcr-ext",
    orgId: "org-dlf-partners",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    name: "Golf Course Extension Road",
    slug: "golf-course-extension-road",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122001",
    tier: "ultra_luxury",
    description: "High-ticket luxury corridor with premier residential complexes, top international schools, and metro connectivity.",
    societiesCount: 14,
    activeUnitsCount: 180,
  },
  {
    id: "area-dwarka-exp",
    orgId: "org-dlf-partners",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    name: "Dwarka Expressway (Sector 102-113)",
    slug: "dwarka-expressway",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122017",
    tier: "luxury",
    description: "Rapidly appreciating micro-market connecting IGI Airport with new commercial hubs.",
    societiesCount: 22,
    activeUnitsCount: 310,
  },
  {
    id: "area-noida-sec43",
    orgId: "org-dlf-partners",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    name: "Sector 43 & Central Noida",
    slug: "sector-43-noida",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201303",
    tier: "luxury",
    description: "Established green residential pocket surrounded by urban forests and golf courses.",
    societiesCount: 8,
    activeUnitsCount: 95,
  },
  {
    id: "area-noida-exp-128",
    orgId: "org-dlf-partners",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    name: "Noida Expressway (Sector 128-137)",
    slug: "noida-expressway-128",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201304",
    tier: "ultra_luxury",
    description: "Exclusive golf community corridor anchored by Jaypee Greens and Max Estates.",
    societiesCount: 12,
    activeUnitsCount: 140,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-vikram",
    orgId: "org-dlf-partners",
    name: "Vikram Malhotra",
    email: "vikram@apexrealty.in",
    phone: "+91 98111 00001",
    role: "owner",
    followUpCompletionRate: 98,
    avgResponseTimeHours: 0.5,
  },
  {
    id: "usr-rahul",
    orgId: "org-dlf-partners",
    name: "Rahul Sharma",
    email: "rahul@apexrealty.in",
    phone: "+91 98101 23456",
    role: "salesperson",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    followUpCompletionRate: 94,
    avgResponseTimeHours: 1.2,
  },
  {
    id: "usr-pooja",
    orgId: "org-dlf-partners",
    name: "Pooja Verma",
    email: "pooja@apexrealty.in",
    phone: "+91 98765 43210",
    role: "salesperson",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    followUpCompletionRate: 89,
    avgResponseTimeHours: 2.1,
  },
  {
    id: "usr-amit",
    orgId: "org-dlf-partners",
    name: "Amit Saxena",
    email: "amit@apexrealty.in",
    phone: "+91 98222 33445",
    role: "salesperson",
    regionId: "reg-delhi",
    regionName: "Delhi Luxury Hub",
    followUpCompletionRate: 82,
    avgResponseTimeHours: 3.4,
  },
];

export const INITIAL_EXTERNAL_ORGS: ExternalOrganization[] = [
  {
    id: "org-ext-dlf",
    orgId: "org-dlf-partners",
    name: "DLF Homes Limited",
    orgType: "developer",
    phone: "+91 124 433 2000",
    email: "sales@dlf.in",
    website: "https://www.dlf.in",
    officeAddress: "DLF Gateway Tower, R Block, DLF City Phase 3, Gurugram",
    city: "Gurugram",
    gstin: "06AAACD1234F1Z5",
    reraId: "HRERA-PKL-GGM-123-2023",
  },
  {
    id: "org-ext-godrej",
    orgId: "org-dlf-partners",
    name: "Godrej Properties",
    orgType: "developer",
    phone: "+91 22 6169 8500",
    email: "customercare@godrejproperties.com",
    website: "https://www.godrejproperties.com",
    officeAddress: "Godrej One, 5th Floor, Pirojshanagar, Eastern Express Hwy, Mumbai",
    city: "Mumbai",
    gstin: "27AABCG5678H1Z2",
    reraId: "UPRERAPRJ7047",
  },
  {
    id: "org-ext-arbour-rwa",
    orgId: "org-dlf-partners",
    name: "The Arbour Residents Welfare Association",
    orgType: "rwa",
    phone: "+91 98110 99887",
    email: "rwa@thearbour.org",
    officeAddress: "Clubhouse Administration Office, DLF The Arbour, Sector 63",
    city: "Gurugram",
    notes: "President meets visitors on Saturday 10-12 AM. Strict vetting for tenant move-in.",
  },
  {
    id: "org-ext-jll",
    orgId: "org-dlf-partners",
    name: "JLL Facility Management Services",
    orgType: "property_management",
    phone: "+91 124 456 7000",
    email: "facilities.arbour@jll.com",
    city: "Gurugram",
    notes: "Manages concierge, lift maintenance, and biometric access keys.",
  },
];

export const INITIAL_TOWERS: ProjectTower[] = [
  {
    id: "tow-dlf-a",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    name: "Tower A",
    towerCode: "TA",
    totalFloors: 39,
    unitsPerFloor: 4,
    elevatorsCount: 4,
    constructionStatus: "under_construction",
    facingDirection: "Golf Course View / South-East",
    totalUnitsCount: 40,
    availableUnitsCount: 12,
    resaleUnitsCount: 4,
  },
  {
    id: "tow-dlf-b",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    name: "Tower B",
    towerCode: "TB",
    totalFloors: 39,
    unitsPerFloor: 4,
    elevatorsCount: 4,
    constructionStatus: "under_construction",
    facingDirection: "Aravalli Hills / South-West",
    totalUnitsCount: 40,
    availableUnitsCount: 14,
    resaleUnitsCount: 6,
  },
  {
    id: "tow-dlf-c",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    name: "Tower C",
    towerCode: "TC",
    totalFloors: 39,
    unitsPerFloor: 4,
    elevatorsCount: 4,
    constructionStatus: "ready",
    facingDirection: "Clubhouse & Lush Greenery",
    totalUnitsCount: 40,
    availableUnitsCount: 12,
    resaleUnitsCount: 8,
  },
  {
    id: "tow-gw-a",
    orgId: "org-dlf-partners",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    name: "Tower A",
    towerCode: "T1",
    totalFloors: 34,
    unitsPerFloor: 4,
    elevatorsCount: 3,
    constructionStatus: "ready",
    facingDirection: "Urban Forest / East",
    totalUnitsCount: 48,
    availableUnitsCount: 14,
    resaleUnitsCount: 5,
  },
  {
    id: "tow-max-t1",
    orgId: "org-dlf-partners",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    name: "Tower 1",
    towerCode: "T1",
    totalFloors: 28,
    unitsPerFloor: 2,
    elevatorsCount: 3,
    constructionStatus: "ready",
    facingDirection: "Golf Course Direct View",
    totalUnitsCount: 40,
    availableUnitsCount: 8,
    resaleUnitsCount: 3,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-dlf-arbour",
    orgId: "org-dlf-partners",
    name: "DLF The Arbour",
    developer: "DLF Homes Limited",
    location: "Sector 63, Golf Course Extension Rd",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    areaId: "area-gcr-ext",
    areaName: "Golf Course Extension Road",
    societyType: "high_rise",
    totalTowers: 5,
    totalUnitsCount: 1137,
    possessionYear: 2027,
    gatedSecurityType: "3_tier",
    reraRegistrationNumber: "RC/REP/HARERA/GGM/671/403/2023/15",
    masterAmenities: ["85,000 sq ft Clubhouse", "Olympic Lap Pool", "3 Covered Car Parks per unit", "Private Elevator Lobbies"],
    maintenanceContactPhone: "+91 98110 54321",
    societyOfficeAddress: "Sector 63, Golf Course Extension Road, Gurugram",
    priceRange: "₹6.5 Cr - ₹9.8 Cr",
    status: "active",
    activeLeadsCount: 48,
    siteVisitsCount: 16,
    totalUnits: 120,
    availableUnitsCount: 38,
    bookedUnitsCount: 82,
    resaleOpportunitiesCount: 18,
    contacts: [
      { id: "pc-1", name: "Sanjay Kaul (Site Head)", role: "builder", phone: "+91 99999 11223" },
      { id: "pc-1b", name: "Ram Singh (Gate 2 Guard)", role: "guard", phone: "+91 98110 54321" },
      { id: "pc-1c", name: "Ar. Sunita Menon", role: "architect", phone: "+91 98201 99887" },
    ],
  },
  {
    id: "proj-godrej-woods",
    orgId: "org-dlf-partners",
    name: "Godrej Woods",
    developer: "Godrej Properties",
    location: "Sector 43",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    areaId: "area-noida-sec43",
    areaName: "Sector 43 & Central Noida",
    societyType: "gated_community",
    totalTowers: 8,
    totalUnitsCount: 800,
    possessionYear: 2026,
    gatedSecurityType: "3_tier",
    reraRegistrationNumber: "UPRERAPRJ7047",
    masterAmenities: ["600 Forest Trees", "Twin Clubhouses", "Infinity Pool", "Whispering Forest Trails"],
    priceRange: "₹2.4 Cr - ₹4.8 Cr",
    status: "active",
    activeLeadsCount: 36,
    siteVisitsCount: 12,
    totalUnits: 96,
    availableUnitsCount: 24,
    bookedUnitsCount: 72,
    resaleOpportunitiesCount: 12,
    contacts: [
      { id: "pc-2", name: "Rohit Mathur (Sales Lead)", role: "builder", phone: "+91 98118 77665" },
      { id: "pc-2b", name: "Dinesh Sharma (Tower 4 Guard)", role: "guard", phone: "+91 98711 22334" },
    ],
  },
  {
    id: "proj-m3m-crown",
    orgId: "org-dlf-partners",
    name: "M3M Crown",
    developer: "M3M Group",
    location: "Sector 111, Dwarka Expressway",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    areaId: "area-dwarka-exp",
    areaName: "Dwarka Expressway (Sector 102-113)",
    societyType: "luxury_township",
    totalTowers: 11,
    totalUnitsCount: 1400,
    possessionYear: 2027,
    gatedSecurityType: "3_tier",
    reraRegistrationNumber: "HRERA-PKL-GGM-1402-2023",
    priceRange: "₹2.8 Cr - ₹5.2 Cr",
    status: "active",
    activeLeadsCount: 29,
    siteVisitsCount: 9,
    totalUnits: 140,
    availableUnitsCount: 52,
    bookedUnitsCount: 88,
    resaleOpportunitiesCount: 15,
    contacts: [
      { id: "pc-3", name: "Kapil Oberoi (Sales VP)", role: "builder", phone: "+91 98100 88990" },
      { id: "pc-3b", name: "Kailash (Main Gate Guard)", role: "guard", phone: "+91 98990 12345" },
    ],
  },
  {
    id: "proj-max-128",
    orgId: "org-dlf-partners",
    name: "Max Estates 128",
    developer: "Max Estates",
    location: "Noida Expressway, Sector 128",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    areaId: "area-noida-exp-128",
    areaName: "Noida Expressway (Sector 128-137)",
    societyType: "high_rise",
    totalTowers: 3,
    totalUnitsCount: 260,
    possessionYear: 2026,
    gatedSecurityType: "biometric_smart",
    priceRange: "₹4.5 Cr - ₹9.0 Cr",
    status: "active",
    activeLeadsCount: 22,
    siteVisitsCount: 7,
    totalUnits: 80,
    availableUnitsCount: 18,
    bookedUnitsCount: 62,
    resaleOpportunitiesCount: 7,
    contacts: [
      { id: "pc-4", name: "Tarun Gupta (Site Director)", role: "builder", phone: "+91 98188 44556" },
    ],
  },
];

export const INITIAL_UNITS: ProjectUnit[] = [
  // DLF The Arbour Tower C
  {
    id: "unit-dlf-c1204",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    towerId: "tow-dlf-c",
    tower: "Tower C",
    unitNumber: "C-1204",
    floor: 12,
    configuration: "3 BHK + Servant",
    unitType: "apartment",
    sizeSqFt: 1850,
    superAreaSqFt: 2450,
    carpetAreaSqFt: 1720,
    builtUpAreaSqFt: 2050,
    balconiesCount: 3,
    bathroomsCount: 4,
    parkingSlots: 2,
    parkingType: "covered",
    isCornerUnit: true,
    furnishingStatus: "semi_furnished",
    physicalCondition: "brand_new",
    viewType: "Golf Course & Central Greens",
    price: 65000000,
    askingPrice: 65000000,
    estimatedMarketPrice: 66000000,
    lastTransactedPrice: 58000000,
    lastTransactedDate: "2024-03-15",
    maintenanceMonthly: 12500,
    expectedMonthlyRent: 95000,
    rentalYieldPct: 1.75,
    status: "site_visit",
    occupancyStatus: "vacant",
    sellerIntent: "actively_selling",
    sellerTargetTimeline: "Immediate (30-45 days)",
    listingStatus: "exclusive_mandate",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-20T10:00:00Z",
    assignedLeadId: "lead-101",
    assignedBuyerName: "Rajesh Singhal",
    facing: "North-East / Park Facing",
    keyLocation: "With Society Facility Desk (Key tag #C1204)",
    unitAmenities: ["Italian Marble Flooring", "VRV Air Conditioning", "Modular Kitchen with Miele Appliances"],
    notes: "Owner Mr. Rajesh Sharma is NRI based in Singapore. Power of Attorney held by brother in Gurgaon.",
  },
  {
    id: "unit-dlf-c1205",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    towerId: "tow-dlf-c",
    tower: "Tower C",
    unitNumber: "C-1205",
    floor: 12,
    configuration: "3 BHK + Servant",
    unitType: "apartment",
    sizeSqFt: 1850,
    superAreaSqFt: 2450,
    carpetAreaSqFt: 1720,
    price: 64000000,
    askingPrice: 64000000,
    estimatedMarketPrice: 64500000,
    maintenanceMonthly: 12500,
    expectedMonthlyRent: 92000,
    status: "available",
    occupancyStatus: "vacant",
    sellerIntent: "willing_to_sell_at_price",
    listingStatus: "open_market",
    verificationStatus: "verified",
    facing: "City Skyline / East",
  },
  {
    id: "unit-dlf-c1402",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    towerId: "tow-dlf-c",
    tower: "Tower C",
    unitNumber: "C-1402",
    floor: 14,
    configuration: "4 BHK Luxury",
    unitType: "apartment",
    sizeSqFt: 2400,
    superAreaSqFt: 3150,
    carpetAreaSqFt: 2320,
    balconiesCount: 4,
    bathroomsCount: 5,
    parkingSlots: 3,
    price: 81000000,
    askingPrice: 82500000,
    estimatedMarketPrice: 82000000,
    status: "hold",
    occupancyStatus: "owner_occupied",
    sellerIntent: "soft_testing_market",
    listingStatus: "private_pocket",
    verificationStatus: "verified",
    assignedLeadId: "lead-105",
    assignedBuyerName: "Rohit Bansal",
    facing: "Aravalli Range View",
    notes: "Owner willing to sell if buyer meets ₹8.25 Cr all-inclusive.",
  },
  {
    id: "unit-dlf-c1501",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    towerId: "tow-dlf-c",
    tower: "Tower C",
    unitNumber: "C-1501",
    floor: 15,
    configuration: "4 BHK Penthouse",
    unitType: "penthouse",
    sizeSqFt: 3100,
    superAreaSqFt: 4200,
    carpetAreaSqFt: 3100,
    balconiesCount: 4,
    bathroomsCount: 5,
    parkingSlots: 3,
    isCornerUnit: true,
    price: 98000000,
    askingPrice: 98000000,
    estimatedMarketPrice: 99000000,
    status: "available",
    occupancyStatus: "vacant",
    sellerIntent: "actively_selling",
    listingStatus: "exclusive_mandate",
    verificationStatus: "verified",
    facing: "Panoramic Dual Balcony",
  },
  {
    id: "unit-dlf-b0802",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    towerId: "tow-dlf-b",
    tower: "Tower B",
    unitNumber: "B-0802",
    floor: 8,
    configuration: "3 BHK",
    unitType: "apartment",
    sizeSqFt: 1750,
    superAreaSqFt: 2200,
    price: 61000000,
    status: "sold",
    occupancyStatus: "rented",
    sellerIntent: "not_selling",
    listingStatus: "unlisted",
    verificationStatus: "verified",
    facing: "Internal Garden",
  },

  // Godrej Woods Tower A
  {
    id: "unit-gw-a1402",
    orgId: "org-dlf-partners",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    towerId: "tow-gw-a",
    tower: "Tower A",
    unitNumber: "A-1402",
    floor: 14,
    configuration: "3 BHK + Study",
    unitType: "apartment",
    sizeSqFt: 1550,
    superAreaSqFt: 2050,
    price: 28500000,
    askingPrice: 29000000,
    status: "negotiation",
    occupancyStatus: "vacant",
    sellerIntent: "actively_selling",
    listingStatus: "exclusive_mandate",
    verificationStatus: "verified",
    assignedLeadId: "lead-102",
    assignedBuyerName: "Ananya Deshmukh",
    facing: "Forest Trail Facing",
  },
  {
    id: "unit-max-t1-1804",
    orgId: "org-dlf-partners",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    towerId: "tow-max-t1",
    tower: "Tower 1",
    unitNumber: "T1-1804",
    floor: 18,
    configuration: "4 BHK Grand Suite",
    unitType: "apartment",
    sizeSqFt: 3400,
    superAreaSqFt: 4600,
    price: 72000000,
    askingPrice: 72000000,
    status: "booked",
    occupancyStatus: "under_fitout",
    sellerIntent: "not_selling",
    assignedLeadId: "lead-104",
    assignedBuyerName: "Suresh Gupta",
    facing: "Golf Course View",
  },
];

export const INITIAL_PEOPLE: Person[] = [
  {
    id: "per-rajesh-sharma",
    orgId: "org-dlf-partners",
    name: "Rajesh Sharma",
    phone: "+91 98100 11204",
    phoneNormalized: "+919810011204",
    email: "rajesh.sharma@singaporetech.io",
    city: "Singapore / Gurugram",
    occupation: "Director, Global Cloud Architecture",
    vipTier: "nri",
    source: "Referral",
    preferredConfiguration: "3 BHK / 4 BHK",
    budget: 70000000,
    associatedProjectNames: ["DLF The Arbour"],
    createdAt: "2024-01-10T10:00:00Z",
    tags: ["NRI", "Investor", "Owner DLF Arbour C-1204"],
  },
  {
    id: "per-singhal",
    orgId: "org-dlf-partners",
    name: "Rajesh Singhal",
    phone: "+91 98112 34567",
    phoneNormalized: "+919811234567",
    email: "rajesh.singhal@hitechmetals.com",
    city: "Delhi",
    occupation: "Managing Director, Hi-Tech Metals Ltd",
    vipTier: "ultra_hni",
    source: "Direct",
    preferredConfiguration: "3 BHK Luxury",
    budget: 65000000,
    associatedProjectNames: ["DLF The Arbour"],
    createdAt: "2026-08-15T09:30:00Z",
    tags: ["Buyer", "Active Site Visit", "Ready Cheque"],
  },
  {
    id: "per-deshmukh",
    orgId: "org-dlf-partners",
    name: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    phoneNormalized: "+919876543210",
    email: "ananya.d@fintechglobal.com",
    city: "Noida",
    occupation: "VP Product, FinTech Global",
    vipTier: "hni",
    source: "Portal Inbound",
    preferredConfiguration: "3 BHK + Study",
    budget: 28500000,
    associatedProjectNames: ["Godrej Woods"],
    createdAt: "2026-08-14T11:20:00Z",
  },
  {
    id: "per-bansal",
    orgId: "org-dlf-partners",
    name: "Rohit Bansal",
    phone: "+91 98105 55667",
    phoneNormalized: "+919810555667",
    email: "rohit.bansal@dubaiholdings.ae",
    city: "Dubai",
    occupation: "Managing Partner, Venture Capital",
    vipTier: "nri",
    source: "WhatsApp Campaign",
    preferredConfiguration: "4 BHK Luxury",
    budget: 85000000,
    associatedProjectNames: ["DLF The Arbour"],
    createdAt: "2026-08-18T14:45:00Z",
  },
  {
    id: "per-sec-arbour",
    orgId: "org-dlf-partners",
    name: "Col. Pradeep Bakshi (Retd.)",
    phone: "+91 98110 88776",
    phoneNormalized: "+919811088776",
    email: "secretary@thearbour.org",
    city: "Gurugram",
    occupation: "Secretary, The Arbour RWA",
    vipTier: "standard",
    source: "Society Management",
    createdAt: "2024-06-01T10:00:00Z",
    tags: ["RWA Secretary", "Key Influencer"],
  },
];

export const INITIAL_RELATIONSHIPS: EntityRelationship[] = [
  // Rajesh Sharma owns Unit C-1204
  {
    id: "rel-1",
    orgId: "org-dlf-partners",
    subjectType: "person",
    subjectId: "per-rajesh-sharma",
    subjectName: "Rajesh Sharma",
    subjectPhone: "+91 98100 11204",
    relationshipType: "owns",
    targetType: "unit",
    targetId: "unit-dlf-c1204",
    targetName: "DLF The Arbour • C-1204",
    validFrom: "2024-03-15",
    isCurrent: true,
    confidenceScore: 100,
    verificationStatus: "verified",
    provenanceSource: "registry_document",
    commercialTerms: { purchasePriceINR: 58000000, registryDate: "2024-03-15" },
    notes: "Purchased in initial launch booking. Clear registry title.",
    createdAt: "2024-03-15T12:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  // Col Bakshi is RWA Secretary for DLF The Arbour
  {
    id: "rel-2",
    orgId: "org-dlf-partners",
    subjectType: "person",
    subjectId: "per-sec-arbour",
    subjectName: "Col. Pradeep Bakshi (Retd.)",
    subjectPhone: "+91 98110 88776",
    relationshipType: "rwa_secretary",
    targetType: "project",
    targetId: "proj-dlf-arbour",
    targetName: "DLF The Arbour",
    validFrom: "2025-01-01",
    isCurrent: true,
    confidenceScore: 100,
    verificationStatus: "verified",
    provenanceSource: "society_directory",
    notes: "Elected RWA Secretary. Key person for society approvals and visitor badges.",
    createdAt: "2025-01-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  // DLF developed DLF The Arbour
  {
    id: "rel-3",
    orgId: "org-dlf-partners",
    subjectType: "organization",
    subjectId: "org-ext-dlf",
    subjectName: "DLF Homes Limited",
    relationshipType: "developed_by",
    targetType: "project",
    targetId: "proj-dlf-arbour",
    targetName: "DLF The Arbour",
    validFrom: "2023-01-01",
    isCurrent: true,
    confidenceScore: 100,
    verificationStatus: "verified",
    provenanceSource: "builder_data",
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2023-01-01T10:00:00Z",
  },
  // Rahul Sharma (sales rep) represents seller Rajesh Sharma
  {
    id: "rel-4",
    orgId: "org-dlf-partners",
    subjectType: "user",
    subjectId: "usr-rahul",
    subjectName: "Rahul Sharma (Apex Realty)",
    relationshipType: "representing_seller",
    targetType: "unit",
    targetId: "unit-dlf-c1204",
    targetName: "DLF The Arbour • C-1204",
    validFrom: "2026-07-01",
    isCurrent: true,
    confidenceScore: 95,
    verificationStatus: "verified",
    provenanceSource: "salesperson_entry",
    commercialTerms: { targetPriceINR: 65000000, commissionPct: 1.0 },
    notes: "Mandate to close sale before Diwali. Owner available on WhatsApp.",
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
];

export const INITIAL_PROPERTY_FACTS: PropertyFact[] = [
  {
    id: "fact-1",
    orgId: "org-dlf-partners",
    entityType: "project",
    entityId: "proj-dlf-arbour",
    category: "visitor_access_rules",
    title: "Client Site Visit Security Protocol",
    factStatement: "Visitor entry permitted via Gate 2 only. Prior notification via MyGate QR code is mandatory for client vehicles. Security guard Ram Singh (+91 98110 54321) issues temporary clubhouse passes.",
    verificationTier: "verified",
    confidencePct: 100,
    sourceReference: "Society Admin Office Notice",
    createdAt: "2026-07-15T10:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "fact-2",
    orgId: "org-dlf-partners",
    entityType: "unit",
    entityId: "unit-dlf-c1204",
    category: "owner_preferences",
    title: "Owner Communication Timing & Pricing Flexibility",
    factStatement: "Owner Rajesh Sharma is in Singapore (+8 hrs time diff). Always WhatsApp him post 7:00 PM IST. He is willing to close at ₹6.40 Cr for immediate 30-day RTGS payment without loan contingency.",
    verificationTier: "verified",
    confidencePct: 95,
    sourceReference: "Call log with owner on 2026-08-18",
    createdAt: "2026-08-18T19:30:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "fact-3",
    orgId: "org-dlf-partners",
    entityType: "project",
    entityId: "proj-dlf-arbour",
    category: "pricing_intelligence",
    title: "Recent Secondary Market Price Benchmark",
    factStatement: "Tower B 8th floor transacted at ₹24,800/sqft last month. Asking rates in Tower C are holding strong between ₹26,000 - ₹27,500/sqft due to direct park view.",
    verificationTier: "historical",
    confidencePct: 90,
    sourceReference: "Sub-registrar registry record & broker network",
    createdAt: "2026-08-10T11:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "fact-4",
    orgId: "org-dlf-partners",
    entityType: "tower",
    entityId: "tow-dlf-c",
    category: "construction_quality",
    title: "Tower C Lift & Fitout Schedule",
    factStatement: "Service elevator is operational 24/7. High-speed passenger lifts 1 & 2 undergo weekly maintenance every Tuesday 2:00 PM - 4:00 PM.",
    verificationTier: "verified",
    confidencePct: 100,
    sourceReference: "JLL Facility Manager",
    createdAt: "2026-08-01T09:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
];

export const INITIAL_PRICE_HISTORY: UnitPriceHistory[] = [
  {
    id: "uph-1",
    orgId: "org-dlf-partners",
    unitId: "unit-dlf-c1204",
    eventType: "asking_price_change",
    oldPrice: 68000000,
    newPrice: 65000000,
    pricePerSqFt: 26530,
    source: "salesperson_update",
    notes: "Owner revised asking price down from ₹6.8 Cr to ₹6.5 Cr to accelerate sale.",
    effectiveDate: "2026-08-10",
    createdAt: "2026-08-10T10:00:00Z",
  },
  {
    id: "uph-2",
    orgId: "org-dlf-partners",
    unitId: "unit-dlf-c1204",
    eventType: "transaction_closed",
    newPrice: 58000000,
    pricePerSqFt: 23673,
    source: "registry_record",
    notes: "Original allotment transaction by developer DLF.",
    effectiveDate: "2024-03-15",
    createdAt: "2024-03-15T12:00:00Z",
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-101",
    orgId: "org-dlf-partners",
    personId: "per-singhal",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    email: "rajesh.singhal@hitechmetals.com",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 65000000,
    stage: "site_visit",
    source: "Website Direct Inbound",
    dealType: "resale",
    leadScore: 92,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 88,
    dealHealthReason: "High momentum: Site visit scheduled for Sunday, budget pre-verified.",
    recommendedAction: "Escort buyer to Tower C Unit 1204 and present park-view comparison sheet.",
    configurationPreference: "3 BHK + Servant",
    preferredFloor: "High (10-15)",
    facingPreference: "North-East / Park Facing",
    parkingRequirement: "2 Covered Car Parks",
    buyerIntent: "End-User (Primary Residence for family)",
    decisionMakers: "Buyer & Brother",
    buyingSignals: ["Budget fully liquid", "Pre-approved HDFC loan", "Wife shortlisted park view"],
    assignedUnitId: "unit-dlf-c1204",
    assignedUnitNumber: "C-1204",
    unitId: "unit-dlf-c1204",
    daysInStage: 2,
    lastActivityText: "Site visit confirmed for Sunday 11 AM",
    lastActivityAt: "2026-08-20T10:30:00Z",
    nextFollowUpAt: "Today, 11:00 AM",
    followUpStatus: "due_today",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "lead-102",
    orgId: "org-dlf-partners",
    personId: "per-deshmukh",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    email: "ananya.d@fintechglobal.com",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    budget: 28500000,
    stage: "negotiation",
    source: "Portal Inbound",
    dealType: "primary_sale",
    leadScore: 84,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 82,
    dealHealthReason: "Final price negotiation ongoing with builder sales VP.",
    recommendedAction: "Offer 20:80 subvention payment scheme to close by Friday.",
    configurationPreference: "3 BHK + Study",
    assignedUnitId: "unit-gw-a1402",
    assignedUnitNumber: "A-1402",
    unitId: "unit-gw-a1402",
    daysInStage: 3,
    lastActivityText: "Payment plan options shared on WhatsApp",
    lastActivityAt: "2026-08-19T16:20:00Z",
    nextFollowUpAt: "Tomorrow, 2:30 PM",
    followUpStatus: "upcoming",
    createdAt: "2026-08-14T11:20:00Z",
  },
  {
    id: "lead-103",
    orgId: "org-dlf-partners",
    personId: "per-bansal",
    personName: "Rohit Bansal (NRI)",
    phone: "+91 98105 55667",
    email: "rohit.bansal@dubaiholdings.ae",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon Hub",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 85000000,
    stage: "qualified",
    source: "WhatsApp Campaign",
    dealType: "resale",
    leadScore: 88,
    leadScoreLabel: "Hot",
    dealHealth: "neutral",
    dealHealthScore: 68,
    dealHealthReason: "NRI buyer requested video walkthrough of Tower C 4BHK Penthouse.",
    recommendedAction: "Send curated WhatsApp video walkthrough of Unit C-1402 & C-1501.",
    configurationPreference: "4 BHK Luxury",
    assignedUnitId: "unit-dlf-c1402",
    assignedUnitNumber: "C-1402",
    unitId: "unit-dlf-c1402",
    daysInStage: 4,
    lastActivityText: "Video walkthrough requested",
    lastActivityAt: "2026-08-18T14:45:00Z",
    nextFollowUpAt: "Today, 4:00 PM",
    followUpStatus: "due_today",
    createdAt: "2026-08-18T14:45:00Z",
  },
  {
    id: "lead-104",
    orgId: "org-dlf-partners",
    personId: "per-bansal",
    personName: "Suresh Gupta",
    phone: "+91 98188 12345",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    regionId: "reg-noida",
    regionName: "Noida Hub",
    salespersonId: "usr-amit",
    salespersonName: "Amit Saxena",
    budget: 72000000,
    stage: "won",
    source: "Direct Referral",
    dealType: "primary_sale",
    leadScore: 100,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 100,
    dealHealthReason: "Deal successfully won. Token cheque ₹25L collected.",
    recommendedAction: "Execute builder-buyer agreement and issue payment receipt.",
    configurationPreference: "4 BHK Grand Suite",
    assignedUnitId: "unit-max-t1-1804",
    assignedUnitNumber: "T1-1804",
    unitId: "unit-max-t1-1804",
    daysInStage: 1,
    lastActivityText: "Booking cheque received",
    lastActivityAt: "2026-08-17T18:00:00Z",
    followUpStatus: "completed",
    createdAt: "2026-08-10T12:00:00Z",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "tsk-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Confirm Site Visit & Pick-up arrangement with brother",
    dueDate: "Today",
    dueTime: "11:00 AM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-2",
    orgId: "org-dlf-partners",
    leadId: "lead-103",
    personName: "Rohit Bansal (NRI)",
    phone: "+91 98105 55667",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Send WhatsApp video walkthrough of Tower C Unit 1402 & 1501",
    dueDate: "Today",
    dueTime: "4:00 PM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-3",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    projectName: "Godrej Woods",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    title: "Follow up on HDFC home loan pre-approval & floor rise sanction",
    dueDate: "Tomorrow",
    dueTime: "2:30 PM",
    status: "upcoming",
    priority: "medium",
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    unitId: "unit-dlf-c1204",
    projectId: "proj-dlf-arbour",
    personName: "Rajesh Singhal",
    userId: "usr-rahul",
    userName: "Rahul Sharma",
    type: "call",
    outcome: "site_visit_booked",
    outcomeLabel: "Site Visit Booked",
    notes: "Customer confirmed for Sunday 11 AM at DLF Site Office for Unit C-1204.",
    scheduledFollowUpAt: "Today, 11:00 AM",
    createdAt: "2026-08-20T10:30:00Z",
  },
  {
    id: "act-2",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    unitId: "unit-gw-a1402",
    projectId: "proj-godrej-woods",
    personName: "Ananya Deshmukh",
    userId: "usr-pooja",
    userName: "Pooja Verma",
    type: "whatsapp",
    notes: "Shared payment schedule 20:80 and floor plan layout for unit #A-1402.",
    createdAt: "2026-08-19T16:20:00Z",
  },
  {
    id: "act-3",
    orgId: "org-dlf-partners",
    leadId: "lead-104",
    unitId: "unit-max-t1-1804",
    projectId: "proj-max-128",
    personName: "Suresh Gupta",
    userId: "usr-amit",
    userName: "Amit Saxena",
    type: "booking",
    outcome: "interested",
    outcomeLabel: "Booking Token Received",
    notes: "Cheque handed over for Max 128 Unit T1-1804. KYC documents collected.",
    createdAt: "2026-08-17T18:00:00Z",
  },
];

export const INITIAL_DOCUMENTS: CRMDocument[] = [
  {
    id: "doc-1",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    title: "DLF The Arbour - Official Luxury Master E-Brochure & Floor Specs",
    fileUrl: "https://dlf.in/the-arbour-brochure.pdf",
    type: "brochure",
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "doc-2",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    title: "Tower A, B & C - Architectural Floor Plans (2,450 to 4,200 sq ft)",
    fileUrl: "https://dlf.in/the-arbour-tower-plans.pdf",
    type: "floor_plan",
    createdAt: "2026-08-02T11:30:00Z",
  },
  {
    id: "doc-3",
    orgId: "org-dlf-partners",
    projectId: "proj-max-128",
    title: "Max Estates 128 Noida - Project Brochure & Club Amenities Spec",
    fileUrl: "https://maxestates.in/max-128-brochure.pdf",
    type: "brochure",
    createdAt: "2026-08-03T14:00:00Z",
  },
  {
    id: "doc-4",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    title: "Rajesh Singhal - PAN & Aadhar KYC Verification Copy",
    fileUrl: "https://storage.ecosystemrealty.in/kyc/rajesh-singhal-kyc.pdf",
    type: "kyc",
    createdAt: "2026-08-18T12:00:00Z",
  },
];

export const INITIAL_SELLER_OPPORTUNITIES: SellerOpportunity[] = [
  {
    id: "opp-camellias-1402",
    orgId: "org-dlf-partners",
    unitId: "unit-camellias-a1402",
    unitTitle: "The Camellias • Tower A-1402",
    projectName: "DLF The Camellias",
    tower: "Tower A",
    unitNumber: "1402",
    ownerId: "per-vikram-singhania",
    ownerName: "Vikram Singhania",
    ownerPhone: "+91 98111 22334",
    signalType: "tenancy_expiring",
    signalStrength: 92,
    estimatedValuation: 420000000,
    suggestedPitch: "Tenant agreement expires in 45 days. Golf course facing 4 BHK in Tower A has 3 prospective HNI buyers waiting in the ₹41-43 Cr bracket.",
    urgency: "high",
    status: "detected",
    assignedToUserId: "usr-rahul",
    assignedToUserName: "Rahul Sharma",
    aiRationale: "High rental yield plateau with 38% capital appreciation since 2022 purchase. Owner has indicated openness to portfolio rebalancing.",
    createdAt: "2026-08-20T09:00:00Z",
    updatedAt: "2026-08-25T11:00:00Z",
  },
  {
    id: "opp-arbour-t1-2201",
    orgId: "org-dlf-partners",
    unitId: "unit-arbour-t1-2201",
    unitTitle: "DLF The Arbour • Tower 1-2201",
    projectName: "DLF The Arbour",
    tower: "Tower 1",
    unitNumber: "2201",
    ownerId: "per-sunil-mehta",
    ownerName: "Sunil Mehta",
    ownerPhone: "+91 98188 77665",
    signalType: "vacant_unit",
    signalStrength: 85,
    estimatedValuation: 72000000,
    suggestedPitch: "Unit is currently vacant and costing ₹18,000/mo in holding maintenance. Ready investor demand for 4 BHK in Sector 63.",
    urgency: "medium",
    status: "assigned",
    assignedToUserId: "usr-rahul",
    assignedToUserName: "Rahul Sharma",
    aiRationale: "Unit unrented for 75 days. Investor owner is paying unrecovered maintenance and missing 3.2% annual rental yield.",
    createdAt: "2026-08-22T10:30:00Z",
    updatedAt: "2026-08-24T15:00:00Z",
  },
  {
    id: "opp-max-t1-1804",
    orgId: "org-dlf-partners",
    unitId: "unit-max-t1-1804",
    unitTitle: "Max Estates 128 • Tower 1-1804",
    projectName: "Max Estates 128",
    tower: "Tower 1",
    unitNumber: "1804",
    ownerId: "per-ananya-roy",
    ownerName: "Ananya Roy",
    ownerPhone: "+91 98711 55443",
    signalType: "valuation_request",
    signalStrength: 88,
    estimatedValuation: 94000000,
    suggestedPitch: "Owner requested formal price appraisal following recent floor transaction at ₹22,000/sqft.",
    urgency: "high",
    status: "contacted",
    assignedToUserId: "usr-pooja",
    assignedToUserName: "Pooja Verma",
    aiRationale: "Direct WhatsApp inquiry from owner asking for recent transacted comps in Tower 1.",
    createdAt: "2026-08-23T14:15:00Z",
    updatedAt: "2026-08-25T16:30:00Z",
  },
];

export const INITIAL_SITE_VISIT_BRIEFINGS: SiteVisitBriefing[] = [
  {
    id: "briefing-camellias-1402",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    leadName: "Rajesh Singhal",
    leadPhone: "+91 98100 11223",
    unitId: "unit-camellias-a1402",
    unitTitle: "The Camellias • Tower A-1402 (Floor 14)",
    societyName: "DLF The Camellias",
    activityId: "act-1",
    scheduledAt: "2026-08-27T16:00:00Z",
    gateAccessProtocol: "Access via Gate 2 North Wing. Pre-register buyer vehicle number (DL 1C AB 1234) at visitor kiosk. Collect physical visitor lanyard from Concierge.",
    parkingInstructions: "Dedicated visitor basement stall B1-Bay 42 reserved. Do not park in surface drop-off bay.",
    ownerExpectationsSummary: "Owner Vikram Singhania is firm on ₹40 Cr floor price; expects 20% down payment within 30 days. No lowball discussions during walkthrough.",
    buyerPreferencesSummary: "Buyer prefers uninterrupted Golf Course facing, high floor, strict Vastu North-East orientation, 3 covered car parks.",
    previousObjections: [
      "Concerned about annual club maintenance fee (₹3.5 Lakh/yr)",
      "Questioned morning sun exposure on living balcony",
    ],
    talkingPoints: [
      "Private elevator opens directly into residence foyer",
      "Unblocked 180° views of DLF Golf Course 18th hole",
      "Triple-glazed acoustic soundproof glass installed in master suite",
      "Exclusive mandate: all ownership chain documents verified by legal team",
    ],
    generatedByAi: true,
    viewedBySalespersonAt: "2026-08-27T14:00:00Z",
    createdAt: "2026-08-27T10:00:00Z",
  },
];

export const INITIAL_CATALOG_ITEMS: import("../types/commercial").CatalogItem[] = [
  {
    id: "cat-1",
    orgId: "org-dlf-partners",
    type: "material",
    sku: "CEM-OPC53-ULTR",
    name: "UltraTech OPC 53 Grade Cement (50kg Bag)",
    category: "cement",
    brand: "UltraTech",
    uom: "Bags",
    retailPrice: 420,
    wholesalePrice: 385,
    moq: 200,
    specs: { grade: "53", packaging: "HDPE Bag", isrcertified: true },
    isActive: true,
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "cat-2",
    orgId: "org-dlf-partners",
    type: "material",
    sku: "BRK-RED-CLAY-01",
    name: "Grade-1 Machine-Pressed Red Clay Bricks",
    category: "bricks",
    brand: "RedClays Ltd",
    uom: "Pcs",
    retailPrice: 10.5,
    wholesalePrice: 8.8,
    moq: 5000,
    specs: { size: "9x4x3 inch", compressiveStrength: "10 N/mm2" },
    isActive: true,
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "cat-3",
    orgId: "org-dlf-partners",
    type: "material",
    sku: "MRB-ITL-STAT-18",
    name: "Italian Statuario Marble Slabs (18mm)",
    category: "marble",
    brand: "Carrara Stones",
    uom: "Sq.Ft.",
    retailPrice: 850,
    wholesalePrice: 720,
    moq: 500,
    specs: { thickness: "18mm", finish: "Polished", origin: "Italy" },
    isActive: true,
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "cat-4",
    orgId: "org-dlf-partners",
    type: "material",
    sku: "TIL-GVT-600X1200",
    name: "Kajaria 600x1200mm Glazed Vitrified Tiles",
    category: "tiles",
    brand: "Kajaria",
    uom: "Boxes",
    retailPrice: 1100,
    wholesalePrice: 940,
    moq: 50,
    specs: { dimensions: "600x1200mm", surface: "High Gloss", coverage: "15.5 sqft/box" },
    isActive: true,
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "cat-5",
    orgId: "org-dlf-partners",
    type: "material",
    sku: "STL-TMT-550D-12",
    name: "Tata Tiscon 550D TMT Rebar (12mm)",
    category: "steel",
    brand: "Tata Tiscon",
    uom: "Tonne",
    retailPrice: 68500,
    wholesalePrice: 64200,
    moq: 2,
    specs: { grade: "Fe 550D", diameter: "12mm", standardLength: "12m" },
    isActive: true,
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
];

export const INITIAL_INVENTORY_STOCK: import("../types/commercial").InventoryStock[] = [
  {
    id: "stk-1",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-1",
    locationName: "North Depot",
    batchLot: "LOT-2026-03",
    quantity: 2400,
    lastUpdated: "2026-08-25T00:00:00Z",
  },
  {
    id: "stk-2",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-2",
    locationName: "Kiln Yard 3",
    batchLot: "KILN-9",
    quantity: 85000,
    lastUpdated: "2026-08-25T00:00:00Z",
  },
  {
    id: "stk-3",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-3",
    locationName: "Import Yard A",
    batchLot: "BLOCK-88",
    quantity: 4200,
    lastUpdated: "2026-08-25T00:00:00Z",
  },
  {
    id: "stk-4",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-4",
    locationName: "Central Warehouse",
    batchLot: "BATCH-A4",
    quantity: 620,
    lastUpdated: "2026-08-25T00:00:00Z",
  },
  {
    id: "stk-5",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-5",
    locationName: "Steel Stockyard",
    batchLot: "HEAT-4012",
    quantity: 18,
    lastUpdated: "2026-08-25T00:00:00Z",
  },
];

export const INITIAL_INVENTORY_MOVEMENTS: import("../types/commercial").InventoryMovement[] = [
  {
    id: "mov-1",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-1",
    locationName: "North Depot",
    batchLot: "LOT-2026-03",
    quantityChange: 1000,
    movementType: "receipt",
    notes: "Direct factory rake consignment",
    createdAt: "2026-08-22T00:00:00Z",
  },
  {
    id: "mov-2",
    orgId: "org-dlf-partners",
    catalogItemId: "cat-1",
    locationName: "North Depot",
    batchLot: "LOT-2026-03",
    quantityChange: -400,
    movementType: "dispatch",
    notes: "Dispatched to Sky High Towers project",
    createdAt: "2026-08-24T00:00:00Z",
  },
];

export const INITIAL_DISPATCH_CHALLANS: import("../types/commercial").DispatchChallan[] = [
  {
    id: "chl-1001",
    orgId: "org-dlf-partners",
    orderId: "ord-501",
    challanNumber: "DC-2026-0034",
    vehicleNo: "MH-04-GP-8821",
    driverName: "Ramesh Yadav",
    driverPhone: "+91 98201 12345",
    status: "in_transit",
    dispatchedAt: "2026-08-27T08:00:00Z",
    notes: "Direct site delivery gate 2",
    createdAt: "2026-08-27T08:00:00Z",
    updatedAt: "2026-08-27T08:00:00Z",
    items: [
      {
        id: "chli-1",
        challanId: "chl-1001",
        orderItemId: "ordi-1",
        catalogItemId: "cat-1",
        quantity: 800,
      },
    ],
  },
];

export const INITIAL_ORDERS: import("../types/commercial").Order[] = [
  {
    id: "ord-501",
    orgId: "org-dlf-partners",
    quoteId: "qt-101",
    customerOrgId: "org-ext-1",
    customerName: "L&T Construction (Sky High Project)",
    orderNumber: "ORD-2026-0045",
    status: "partially_fulfilled",
    totalAmount: 924000,
    expectedDeliveryDate: "2026-09-05T00:00:00Z",
    notes: "Deliver in 3 tranches of 800 bags each",
    createdAt: "2026-08-20T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
    items: [
      {
        id: "ordi-1",
        orderId: "ord-501",
        catalogItemId: "cat-1",
        quantity: 2400,
        unitPrice: 385,
        totalPrice: 924000,
        fulfilledQuantity: 800,
        notes: "OPC 53 Bags",
      },
    ],
  },
];

// ==========================================
// BUILDING MATERIALS VERTICAL DEDICATED DATA
// ==========================================

export const INITIAL_MATERIALS_REGIONS: Region[] = [
  { id: "reg-mat-ncr", orgId: "org-jindal-supplies", name: "NCR Central Depot", code: "NCR-DEPOT", activeLeadsCount: 52 },
  { id: "reg-mat-ggn", orgId: "org-jindal-supplies", name: "Gurgaon Materials Yard", code: "GGN-YARD", activeLeadsCount: 44 },
  { id: "reg-mat-noida", orgId: "org-jindal-supplies", name: "Noida Regional Depot", code: "NDA-DEPOT", activeLeadsCount: 28 },
];

export const INITIAL_MATERIALS_USERS: User[] = [
  {
    id: "usr-rajesh",
    orgId: "org-jindal-supplies",
    name: "Rajesh Jindal",
    email: "rajesh@jindalsupplies.in",
    phone: "+91 98111 00222",
    role: "owner",
    regionId: "reg-mat-ncr",
    regionName: "NCR Central Depot",
    followUpCompletionRate: 98,
    avgResponseTimeHours: 0.8,
  },
  {
    id: "usr-sunil",
    orgId: "org-jindal-supplies",
    name: "Sunil Aggarwal",
    email: "sunil@jindalsupplies.in",
    phone: "+91 98111 00333",
    role: "manager",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    followUpCompletionRate: 95,
    avgResponseTimeHours: 1.2,
  },
  {
    id: "usr-ramesh",
    orgId: "org-jindal-supplies",
    name: "Ramesh Patel",
    email: "ramesh@jindalsupplies.in",
    phone: "+91 98111 00444",
    role: "salesperson",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    followUpCompletionRate: 91,
    avgResponseTimeHours: 1.8,
  },
  {
    id: "usr-dinesh",
    orgId: "org-jindal-supplies",
    name: "Dinesh Kumar",
    email: "dinesh@jindalsupplies.in",
    phone: "+91 98111 00555",
    role: "salesperson",
    regionId: "reg-mat-noida",
    regionName: "Noida Regional Depot",
    followUpCompletionRate: 88,
    avgResponseTimeHours: 2.2,
  },
];

export const INITIAL_MATERIALS_PROJECTS: Project[] = [
  {
    id: "proj-mat-cybercity3",
    orgId: "org-jindal-supplies",
    name: "Cyber City Phase 3 Tower D",
    developer: "L&T Construction",
    location: "Sector 29, Gurugram",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    societyType: "commercial_hub",
    priceRange: "5,000 MT Cement Order",
    status: "active",
    activeLeadsCount: 18,
    siteVisitsCount: 6,
    masterAmenities: ["OPC 53 Grade Batching", "Ready Mix Concrete (RMC)", "Direct Bulk Silo Supply"],
    maintenanceContactPhone: "+91 98111 11223",
  },
  {
    id: "proj-mat-dwarka-flyover",
    orgId: "org-jindal-supplies",
    name: "Dwarka Expressway Elevated Corridor Seg 4",
    developer: "Afcons Infrastructure",
    location: "Sector 109, Gurugram",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    societyType: "commercial_hub",
    priceRange: "12,000 MT Slag Cement",
    status: "active",
    activeLeadsCount: 24,
    siteVisitsCount: 10,
    masterAmenities: ["PPC Grade Cement", "24/7 RMC Transit Fleet", "On-site Batching Plant"],
    maintenanceContactPhone: "+91 98111 22334",
  },
  {
    id: "proj-mat-max-square",
    orgId: "org-jindal-supplies",
    name: "Max Square Commercial Hub",
    developer: "Shapoorji Pallonji",
    location: "Sector 129, Noida Expressway",
    regionId: "reg-mat-noida",
    regionName: "Noida Regional Depot",
    societyType: "commercial_hub",
    priceRange: "8,500 MT High-Strength OPC",
    status: "active",
    activeLeadsCount: 15,
    siteVisitsCount: 5,
    masterAmenities: ["Bulk Tanker Delivery", "Compressive Strength Lab Tested", "Daily Site Sampling"],
    maintenanceContactPhone: "+91 98111 33445",
  },
  {
    id: "proj-mat-signature-global",
    orgId: "org-jindal-supplies",
    name: "Signature Global City 93",
    developer: "Ahluwalia Contracts",
    location: "Sector 93, Gurugram",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    societyType: "gated_community",
    priceRange: "3,200 MT PPC 53 Grade",
    status: "active",
    activeLeadsCount: 12,
    siteVisitsCount: 4,
    masterAmenities: ["Weather-Resistant Bags", "Direct Depot Dispatch", "14-Day Credit Khata"],
    maintenanceContactPhone: "+91 98111 44556",
  },
];

export const INITIAL_MATERIALS_UNITS: ProjectUnit[] = [
  {
    id: "unit-mat-silo-1",
    orgId: "org-jindal-supplies",
    projectId: "proj-mat-cybercity3",
    projectName: "Cyber City Phase 3 Tower D",
    tower: "Main Yard",
    unitNumber: "Silo-01 (OPC 53)",
    floor: 1,
    configuration: "OPC 53 Grade Bulk",
    sizeSqFt: 500,
    carpetAreaSqFt: 500,
    facing: "North Yard",
    price: 385,
    status: "available",
  },
  {
    id: "unit-mat-silo-2",
    orgId: "org-jindal-supplies",
    projectId: "proj-mat-dwarka-flyover",
    projectName: "Dwarka Expressway Elevated Corridor Seg 4",
    tower: "Main Yard",
    unitNumber: "Silo-02 (PPC Slag)",
    floor: 1,
    configuration: "PPC Slag Cement",
    sizeSqFt: 500,
    carpetAreaSqFt: 500,
    facing: "North Yard",
    price: 360,
    status: "site_visit",
    assignedBuyerName: "Gurpreet Singh",
  },
  {
    id: "unit-mat-bay-1",
    orgId: "org-jindal-supplies",
    projectId: "proj-mat-signature-global",
    projectName: "Signature Global City 93",
    tower: "Warehouse Bay",
    unitNumber: "Bay-A (Pallet Bags)",
    floor: 1,
    configuration: "50kg Packaged Bags",
    sizeSqFt: 1000,
    carpetAreaSqFt: 1000,
    facing: "East Loading",
    price: 375,
    status: "available",
  },
  {
    id: "unit-mat-rmc-1",
    orgId: "org-jindal-supplies",
    projectId: "proj-mat-max-square",
    projectName: "Max Square Commercial Hub",
    tower: "Transit Mixer Fleet",
    unitNumber: "TM-04 (M35 Grade)",
    floor: 1,
    configuration: "RMC Ready Mix Concrete",
    sizeSqFt: 300,
    carpetAreaSqFt: 300,
    facing: "Dispatch Bay",
    price: 4200,
    status: "booked",
    assignedBuyerName: "Manoj Chawla",
  },
];

export const INITIAL_MATERIALS_PEOPLE: Person[] = [
  {
    id: "per-mat-gurpreet",
    orgId: "org-jindal-supplies",
    name: "Gurpreet Singh",
    fullName: "Gurpreet Singh (Chief Site Engineer)",
    phone: "+91 98111 88220",
    phoneNormalized: "+919811188220",
    email: "gurpreet.singh@afcons.com",
    city: "Gurugram",
    companyName: "Afcons Infrastructure",
    designation: "Chief Project Engineer",
    budget: 4500000,
    createdAt: "2026-08-10T00:00:00Z",
  },
  {
    id: "per-mat-manoj",
    orgId: "org-jindal-supplies",
    name: "Manoj Chawla",
    fullName: "Manoj Chawla (Procurement Head)",
    phone: "+91 98710 44551",
    phoneNormalized: "+919871044551",
    email: "manoj.c@shapoorji.com",
    city: "Noida",
    companyName: "Shapoorji Pallonji",
    designation: "VP Procurement",
    budget: 8200000,
    createdAt: "2026-08-12T00:00:00Z",
  },
  {
    id: "per-mat-vikas",
    orgId: "org-jindal-supplies",
    name: "Vikas Aggarwal",
    fullName: "Vikas Aggarwal (Civil Contractor)",
    phone: "+91 99102 33441",
    phoneNormalized: "+919910233441",
    email: "vikas@aggarwalinfra.com",
    city: "Gurugram",
    companyName: "Aggarwal Infra Contracts",
    designation: "Managing Contractor",
    budget: 1800000,
    createdAt: "2026-08-14T00:00:00Z",
  },
  {
    id: "per-mat-harish",
    orgId: "org-jindal-supplies",
    name: "Harish Rao",
    fullName: "Harish Rao (Project Director)",
    phone: "+91 98200 66778",
    phoneNormalized: "+919820066778",
    email: "harish.rao@lntconstruction.com",
    city: "Gurugram",
    companyName: "L&T Construction",
    designation: "Project Director",
    budget: 15000000,
    createdAt: "2026-08-15T00:00:00Z",
  },
];

export const INITIAL_MATERIALS_LEADS: Lead[] = [
  {
    id: "lead-mat-201",
    orgId: "org-jindal-supplies",
    personId: "per-mat-gurpreet",
    personName: "Gurpreet Singh (Afcons Infra)",
    phone: "+91 98111 88220",
    phoneNormalized: "+919811188220",
    email: "gurpreet.singh@afcons.com",
    projectId: "proj-mat-dwarka-flyover",
    projectName: "Dwarka Expressway Elevated Corridor Seg 4",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    salespersonId: "usr-ramesh",
    salespersonName: "Ramesh Patel",
    budget: 4500000,
    stage: "negotiation",
    source: "Site Inbound / Dealer Referral",
    dealType: "primary_sale",
    leadScore: 94,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 92,
    dealHealthReason: "PO approval in progress; test cube strength certified.",
    recommendedAction: "Confirm 3,000 bag dispatch batch and lock in ₹385/bag rate.",
    configurationPreference: "OPC 53 Grade (3,000 Bags Bulk Tanker)",
    assignedUnitId: "unit-mat-silo-2",
    assignedUnitNumber: "Silo-02 Bay",
    unitId: "unit-mat-silo-2",
    daysInStage: 2,
    lastActivityText: "Quoted ₹385/bag net of GST; waiting for purchase order sign-off",
    lastActivityAt: "2026-08-20T10:30:00Z",
    nextFollowUpAt: "Today, 4:00 PM",
    followUpStatus: "due_today",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "lead-mat-202",
    orgId: "org-jindal-supplies",
    personId: "per-mat-manoj",
    personName: "Manoj Chawla (Shapoorji Pallonji)",
    phone: "+91 98710 44551",
    phoneNormalized: "+919871044551",
    email: "manoj.c@shapoorji.com",
    projectId: "proj-mat-max-square",
    projectName: "Max Square Commercial Hub",
    regionId: "reg-mat-noida",
    regionName: "Noida Regional Depot",
    salespersonId: "usr-dinesh",
    salespersonName: "Dinesh Kumar",
    budget: 8200000,
    stage: "site_visit",
    source: "Key Account Direct",
    dealType: "primary_sale",
    leadScore: 88,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 85,
    dealHealthReason: "Quality test slump lab test verified. Site visit scheduled for mixer inspection.",
    recommendedAction: "Arrange transit mixer demonstration on site with Chief Quality Officer.",
    configurationPreference: "Ready-Mix Concrete M35 (850 CuM)",
    assignedUnitId: "unit-mat-rmc-1",
    assignedUnitNumber: "TM-04 (M35)",
    unitId: "unit-mat-rmc-1",
    daysInStage: 3,
    lastActivityText: "Quality test lab slump certificate shared on WhatsApp",
    lastActivityAt: "2026-08-19T14:20:00Z",
    nextFollowUpAt: "Tomorrow, 11:30 AM",
    followUpStatus: "upcoming",
    createdAt: "2026-08-16T11:00:00Z",
  },
  {
    id: "lead-mat-203",
    orgId: "org-jindal-supplies",
    personId: "per-mat-vikas",
    personName: "Vikas Aggarwal (Civil Contractor)",
    phone: "+91 99102 33441",
    phoneNormalized: "+919910233441",
    email: "vikas@aggarwalinfra.com",
    projectId: "proj-mat-signature-global",
    projectName: "Signature Global City 93",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    salespersonId: "usr-ramesh",
    salespersonName: "Ramesh Patel",
    budget: 1800000,
    stage: "qualified",
    source: "Dealer Counter Inbound",
    dealType: "primary_sale",
    leadScore: 78,
    leadScoreLabel: "Warm",
    dealHealth: "strong",
    dealHealthScore: 80,
    dealHealthReason: "Credit check verified; contractor requires 14-day Khata terms.",
    recommendedAction: "Send formal Khata credit agreement and sample pallets.",
    configurationPreference: "Ambuja Kawach Waterproof Cement (1,200 Bags)",
    assignedUnitId: "unit-mat-bay-1",
    assignedUnitNumber: "Bay-A Pallet",
    unitId: "unit-mat-bay-1",
    daysInStage: 1,
    lastActivityText: "Sample test bags dispatched to site",
    lastActivityAt: "2026-08-20T08:15:00Z",
    nextFollowUpAt: "Tomorrow, 3:00 PM",
    followUpStatus: "upcoming",
    createdAt: "2026-08-18T10:00:00Z",
  },
  {
    id: "lead-mat-204",
    orgId: "org-jindal-supplies",
    personId: "per-mat-harish",
    personName: "Harish Rao (L&T Construction)",
    phone: "+91 98200 66778",
    phoneNormalized: "+919820066778",
    email: "harish.rao@lntconstruction.com",
    projectId: "proj-mat-cybercity3",
    projectName: "Cyber City Phase 3 Tower D",
    regionId: "reg-mat-ggn",
    regionName: "Gurgaon Materials Yard",
    salespersonId: "usr-dinesh",
    salespersonName: "Dinesh Kumar",
    budget: 15000000,
    stage: "won",
    source: "Tender / Annual Contract",
    dealType: "primary_sale",
    leadScore: 98,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthScore: 99,
    dealHealthReason: "Annual supply tender signed; first delivery batch executed seamlessly.",
    recommendedAction: "Schedule week 2 dispatch challans and invoice submission.",
    configurationPreference: "OPC 53 Grade Bulk + PPC Cement (Annual Supply)",
    assignedUnitId: "unit-mat-silo-1",
    assignedUnitNumber: "Silo-01",
    unitId: "unit-mat-silo-1",
    daysInStage: 5,
    lastActivityText: "First 40MT Bulk Tanker delivered & accepted",
    lastActivityAt: "2026-08-18T16:00:00Z",
    nextFollowUpAt: "Next Week",
    followUpStatus: "completed",
    createdAt: "2026-08-10T09:00:00Z",
  },
];

export const INITIAL_MATERIALS_ACTIVITIES: Activity[] = [
  {
    id: "act-mat-1",
    orgId: "org-jindal-supplies",
    leadId: "lead-mat-201",
    projectId: "proj-mat-dwarka-flyover",
    personName: "Gurpreet Singh (Afcons Infra)",
    userId: "usr-ramesh",
    userName: "Ramesh Patel",
    type: "call",
    outcome: "interested",
    outcomeLabel: "Quote Sent & Slump Test Verified",
    notes: "Confirmed price of ₹385/bag net of GST for 3,000 bags. PO issuance expected today.",
    scheduledFollowUpAt: "Today, 4:00 PM",
    durationSeconds: 320,
    createdAt: "2026-08-20T10:30:00Z",
  },
  {
    id: "act-mat-2",
    orgId: "org-jindal-supplies",
    leadId: "lead-mat-202",
    projectId: "proj-mat-max-square",
    personName: "Manoj Chawla (Shapoorji Pallonji)",
    userId: "usr-dinesh",
    userName: "Dinesh Kumar",
    type: "whatsapp",
    outcome: "interested",
    outcomeLabel: "Lab Slump Certificate Shared",
    notes: "Shared M35 concrete compressive strength test reports from NABL accredited lab.",
    scheduledFollowUpAt: "Tomorrow, 11:30 AM",
    createdAt: "2026-08-19T14:20:00Z",
  },
];

export const INITIAL_MATERIALS_TASKS: Task[] = [
  {
    id: "tsk-mat-1",
    orgId: "org-jindal-supplies",
    leadId: "lead-mat-201",
    personName: "Gurpreet Singh (Afcons Infra)",
    phone: "+91 98111 88220",
    projectName: "Dwarka Expressway Elevated Corridor Seg 4",
    salespersonId: "usr-ramesh",
    salespersonName: "Ramesh Patel",
    title: "Follow-up: Verify PO Sign-off & Confirm First 800 Bags Dispatch",
    dueDate: "Today, 4:00 PM",
    status: "upcoming",
    priority: "high",
  },
  {
    id: "tsk-mat-2",
    orgId: "org-jindal-supplies",
    leadId: "lead-mat-202",
    personName: "Manoj Chawla (Shapoorji Pallonji)",
    phone: "+91 98710 44551",
    projectName: "Max Square Commercial Hub",
    salespersonId: "usr-dinesh",
    salespersonName: "Dinesh Kumar",
    title: "Transit Mixer Demo: Coordinate TM-04 batching trial at site",
    dueDate: "Tomorrow, 11:30 AM",
    status: "upcoming",
    priority: "medium",
  },
];

